---
cf:
  domain: https://domain.com
  api-endpoint: api.domain.com
  skip-ssl-validation: true
  custom-cli-parameters:
    - --verbose
  username: username
  password: password

tasks:
  - cmd: /bin/bash
    args:
      - -c
      - |
        #!/bin/bash

        set -euo pipefail

        echo "Hello, World!"
        ping -c 100 github.com

merkhets:
  - name: app-pushability
    threshold: '3%'
  - name: http-availability
    threshold: '10'
  - name: cf-log-functionality
    threshold: '42%'
  - name: cf-recent-log-functionality
    threshold: '0'
  - name: syslog-functionality
    threshold: '55.555%'

logger-config:
  time-location: UTC
  print-logger-name: true
