---
cf:
  domain: https://domain.com
  api-endpoint: https://api.domain.com
  skip-ssl-validation: true
  username: username
  password: password

tasks:
  - cmd: /bin/bash
    args:
      - -c
      - |
        #!/bin/bash

        set -euo pipefail

        echo "Hello, World!"
        ping -c 100 github.com
    merkhet-whitelist:
      - app-pushability

merkhets:
  - name: app-pushability
    threshold: '3%'
    heartbeat: 1s
  - name: http-availability
    threshold: '10'
  - name: cf-log-functionality
    threshold: '42%'
  - name: cf-recent-log-functionality
    threshold: '0'
  - name: syslog-functionality
    threshold: '55.555%'

logger-config:
  time-location: UTC
  print-logger-name: true
